---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - isync
  - notmuch
  - emacs-notmuch
  become: yes

- name: Ensure maildir exists
  file:
    name: "{{ mail_dir }}"
    state: directory

- name: Install mbsync config
  template:
    src: mbsyncrc.j2
    dest: "{{ lookup('env', 'HOME') }}/.mbsyncrc"

- name: Ensure systemd dir exists
  file:
    name: ~/.config/systemd/user
    state: directory

- name: Install notmuch config
  template:
    src: notmuch-config.j2
    dest: "{{ lookup('env', 'HOME') }}/.notmuch-config"

- name: Ensure emacs.d exists
  file:
    name: ~/.emacs.d
    state: directory

- name: Ensure notmuch loaded by emacs
  lineinfile:
    create: yes
    name: ~/.emacs.d/init.el
    line: (require 'notmuch)

- name: Install units units
  template:
    src: "{{ item }}.j2"
    dest: ~/.config/systemd/user/{{ item }}
  with_items:
  - mbsync.service
  - mbsync.timer
  - notmuch-compact.service
  - notmuch-compact.timer

- name: Enable units
  systemd:
    name: "{{ item }}"
    user: yes
    daemon_reload: yes
    # "restarted" because modified timers
    # don't seem to work quite right otherwise
    state: restarted
    enabled: yes
  with_items:
  - mbsync.timer
  - notmuch-compact.timer
