---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - isync
  - notmuch
  - emacs-notmuch
  become: yes

- name: Ensure maildir exists
  file:
    name: "{{ mail_dir }}"
    state: directory

- name: Install mbsync config
  template:
    src: mbsyncrc.j2
    dest: "{{ lookup('env', 'HOME') }}/.mbsyncrc"

- name: Ensure systemd dir exists
  file:
    name: ~/.config/systemd/user
    state: directory

- name: Install mbsync units
  template:
    src: "mbsync.{{ item }}.j2"
    dest: ~/.config/systemd/user/mbsync.{{ item }}
  with_items:
  - service
  - timer

- name: Enable mbsync timer
  systemd:
    name: mbsync.timer
    user: yes
    daemon_reload: yes
    state: started
    enabled: yes

- name: Install notmuch config
  template:
    src: notmuch-config.j2
    dest: "{{ lookup('env', 'HOME') }}/.notmuch-config"
