---
- name: Install msmtp
  package:
    name: msmtp
    state: present
  become: yes

- name: Deploy msmtprc
  template:
    src: msmtprc.j2
    dest: ~/.msmtprc
    mode: 0400

- name: Use msmtp for sendmail
  alternatives:
    name: mta
    path: /usr/bin/msmtp
    link: /usr/sbin/sendmail
  become: yes
